// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: service.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	BluePanda_Fetch_FullMethodName = "/bluepanda.BluePanda/Fetch"
)

// BluePandaClient is the client API for BluePanda service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BluePandaClient interface {
	Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (BluePanda_FetchClient, error)
}

type bluePandaClient struct {
	cc grpc.ClientConnInterface
}

func NewBluePandaClient(cc grpc.ClientConnInterface) BluePandaClient {
	return &bluePandaClient{cc}
}

func (c *bluePandaClient) Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (BluePanda_FetchClient, error) {
	stream, err := c.cc.NewStream(ctx, &BluePanda_ServiceDesc.Streams[0], BluePanda_Fetch_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &bluePandaFetchClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BluePanda_FetchClient interface {
	Recv() (*FetchResult, error)
	grpc.ClientStream
}

type bluePandaFetchClient struct {
	grpc.ClientStream
}

func (x *bluePandaFetchClient) Recv() (*FetchResult, error) {
	m := new(FetchResult)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BluePandaServer is the server API for BluePanda service.
// All implementations must embed UnimplementedBluePandaServer
// for forward compatibility
type BluePandaServer interface {
	Fetch(*FetchRequest, BluePanda_FetchServer) error
	mustEmbedUnimplementedBluePandaServer()
}

// UnimplementedBluePandaServer must be embedded to have forward compatible implementations.
type UnimplementedBluePandaServer struct {
}

func (UnimplementedBluePandaServer) Fetch(*FetchRequest, BluePanda_FetchServer) error {
	return status.Errorf(codes.Unimplemented, "method Fetch not implemented")
}
func (UnimplementedBluePandaServer) mustEmbedUnimplementedBluePandaServer() {}

// UnsafeBluePandaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BluePandaServer will
// result in compilation errors.
type UnsafeBluePandaServer interface {
	mustEmbedUnimplementedBluePandaServer()
}

func RegisterBluePandaServer(s grpc.ServiceRegistrar, srv BluePandaServer) {
	s.RegisterService(&BluePanda_ServiceDesc, srv)
}

func _BluePanda_Fetch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FetchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BluePandaServer).Fetch(m, &bluePandaFetchServer{stream})
}

type BluePanda_FetchServer interface {
	Send(*FetchResult) error
	grpc.ServerStream
}

type bluePandaFetchServer struct {
	grpc.ServerStream
}

func (x *bluePandaFetchServer) Send(m *FetchResult) error {
	return x.ServerStream.SendMsg(m)
}

// BluePanda_ServiceDesc is the grpc.ServiceDesc for BluePanda service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BluePanda_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bluepanda.BluePanda",
	HandlerType: (*BluePandaServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Fetch",
			Handler:       _BluePanda_Fetch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "service.proto",
}
